### PR TITLE
Use const generics.

### PR DESCRIPTION
**Pull request by ahmedcharles**
This doesn't remove the fields, it uses them to verify that all of the values are right through debug_asserts. I have more PRs that take this approach further.

The only issue with this is that it doesn't work with the trait, because `Self::Target` isn't the same time for each of the various functions.

Anyways, is this a direction that you're open to? Thanks.

### CODE REVIEW

**Comment by sunsided** [comment]
Absolutely, yes. The reason I didn't go for it yet is because of the limited compile-time arithmetic support for const generics.

**Comment by ahmedcharles** [comment]
Are you ok with the PR as is, or would you prefer some changes? Thanks.

**Comment by ahmedcharles** [comment]
ping?

**Comment by sunsided** [comment]
@ahmedcharles Thanks for the implementation! I adjusted it a bit to get rid of the redundant row/column counts. Will merge in a bit.

**Comment by ahmedcharles** [comment]
I should've mentioned that I had a commit to remove those parameters, I didn't submit it because I wanted it to be obvious that the asserts were correct. :)

**Comment by ahmedcharles** [comment]
Thanks.

**Pull request merged**
